  /api/accounts/account:
    get:
      summary: 내 계좌 조회

      tags:
        - Account

      responses:

        '200':
          description: 계좌 조회 성공

          content:
            application/json:

              schema:
                type: object

                properties:

                  success:
                    type: boolean
                    example: true

                  message:
                    type: string
                    example: 계좌 조회 성공

                  data:
                    type: array

                    items:
                      type: object

                      properties:

                        id:
                          type: integer
                          example: 1

                        user_id:
                          type: integer
                          example: 1

                        account_number:
                          type: string
                          example: 100-123-456789

                        account_type:
                          type: string
                          example: demand

                        balance:
                          type: integer
                          example: 500000

                        transfer_limit:
                          type: integer
                          example: 3000000

                        is_admin:
                          type: boolean
                          example: false

                        is_active:
                          type: boolean
                          example: true

                        created_at:
                          type: string
                          format: date-time
                          example: 2026-05-14T11:20:30.000Z

        '401':
          description: 인증 실패

          content:
            application/json:

              schema:
                type: object

                properties:

                  success:
                    type: boolean
                    example: false

                  errorCode:
                    type: string
                    example: INVALID_TOKEN

                  message:
                    type: string
                    example: 토큰 인증 실패

        '404':
          description: 계좌 정보 없음

          content:
            application/json:

              schema:
                type: object

                properties:

                  success:
                    type: boolean
                    example: false

                  errorCode:
                    type: string
                    example: ACCOUNT_NOT_FOUND

                  message:
                    type: string
                    example: 계좌 정보 없음

        '500':
          description: 서버 오류